### ISSUE TITLE
Wrong alignment when element contain list

### ISSUE THREAD

**Issue by tienlocnguyen** [AndreOneti/qml-formatter#11]
When QML element contain a list which marked with [], the next close bracket will be shift to 1 level
For example:
This is wrong
```qml
            ComboBox {
                width: 200
                model: ["500000", "1000000"]
                }  // -> shifted to 1 level
```

But after comment the list, it's correct
```qml
            ComboBox {
                width: 200
                // model: ["500000", "1000000"]
            } // -> Correct
```

**Comment by AndreOneti** [comment]
Thanks for sharing this error, I will work on fixing it.

But this formatter is still under development.
