### ISSUE TITLE
Support ES6 template literals (backtick strings)

### ISSUE THREAD

**Issue by alvinhochun** [AndreOneti/qml-formatter#19]
Currently the syntax highlighting doesn't highlight them as strings, and the formatter mangles the placeholders (dollar sign and curly braces).

![Example](https://user-images.githubusercontent.com/2397650/153877981-ffcf073f-103d-412e-b394-253d39ac0787.png)

**Comment by AndreOneti** [comment]
Can you revalidate this issue?

**Comment by alvinhochun** [comment]
Thanks, the current version has these working :)
