### ISSUE TITLE
Highlight block comments

### ISSUE THREAD

**Issue by alvinhochun** [AndreOneti/qml-formatter#20]
Block comments `/* ... */` are not highlighted correctly.

**Comment by AndreOneti** [comment]
what would be the problem?

Could you explain better what is happening or what should happen?

**Comment by alvinhochun** [comment]
Hi, for a while they didn't get parsed or highlighted as comments. But I rechecked just now and they are highlighted correctly as comments. I don't really know what happened back then but this can be considered resolved.
